### ISSUE TITLE
Make it quick

### ISSUE THREAD

**Issue by matt-gadd** [dojo/site#10]

**Comment by KaneFreeman** [comment]
| Page | Page Size | Load Time |
| --- | :---: | :---: |
| Home | 138.3 KB<sup>1</sup> | 803 ms<sup>1</sup> |
| Blog | **546.9 KB** | 829 ms |
| Blog Post | **349.4 KB** | 820 ms |
| Reference Guides Landing | 89.7 KB | 923 ms |
| Reference Guides | 196.5 KB | 959 ms |
| Examples | 1.5 MB | **1.53 s** |
| Playground | 3.0 MB | 753 ms |
| Roadmap | 82.0 KB | 843 ms |
| Community | 83.5 KB | 807 ms |

- <sup>1</sup> Still a work in progress.
