### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by matt-gadd** [dojo/site#11]

**Comment by KaneFreeman** [comment]
## Audit of current deployed production
https://site-jkqgpcsrkc.now.sh/home

| Page | Large Monitor | Laptop | Tablet | Mobile |
| --- | :---: | :---: | :---: | :---: |
| Home | ✔️ | ✔️ | ❌  | ✔️ |
| Menu / Header | ✔️  | ✔️ | ✔️  | ❌ |
| Blog | ❔  | ❔ | ❔  | ❔ |
| Tutorials Landing | ✔️ | ✔️ | ✔️  | ✔️ |
| Tutorials | ✔️ | ❌ | ❌  | ❌ |
| Reference Guides Landing | ✔️ | ✔️ | ✔️  | ✔️ |
| Reference Guides | ✔️ | ❌ | ❌  | ❌ |
| Examples | ✔️ | ✔️ | ✔️  | ✔️ |
| Playground | ✔️ | ✔️ | ✔️  | ✔️ |
| Community | ✔️ | ✔️ | ✔️  | ✔️ |

## Details
- **Home**
  - **Tablet** - Page width grows as CLI section typing occurs. Tested in Chrome with iPad Pro in Portrait mode (width: 1024).
- **Menu**
  - **Mobile** - A bit small. Maybe 75% width over the current ~50%.
- **Tutorials / Reference Guides** - Same widgets. Should probably be combined with main Menu when in mobile mode.
