### ISSUE TITLE
Include sandbox examples in the site

### ISSUE THREAD

**Issue by agubler** [dojo/site#161]
We have a number of example sandboxes that could be useful for the community but are not especially discoverable, we should find a place on the new site to list/show them.

A couple of suggestions have been to include them on the examples page or to enhance the playground to be able to open them directly in dojo.io.

### List of potential sandboxes (already in the dojo org on codesandbox):

* Basic `icache` example
  * https://codesandbox.io/s/basic-icache-middleware-owpcz
* Advanced `icache` example
  * https://codesandbox.io/s/advanced-icache-middleware-teeig
* ~`@dojo/widgets` - tab controller examples~
  * ~https://codesandbox.io/s/5377l81nkn~
* ~`@dojo/widgets` - combobox examples~
  * ~https://codesandbox.io/s/exciting-golick-oll14jq045~
* ~`@dojo/widgets` - grid examples~
  * ~https://codesandbox.io/s/gifted-meninsky-7zl3wqrxp6~
* ~`@dojo/widgets` - button examples~
  * ~https://codesandbox.io/s/5yw8w6j1rl~
* ~`@dojo/widgets` - time picker examples~
  * ~https://codesandbox.io/s/sad-goodall-6y61v2r3l3~
* ~`@dojo/widgets` - radio example~
  * ~https://codesandbox.io/s/dojo-radio-examples-480r3p1z14~

### List of other sandboxes (not currently in the dojo org on codesandbox):

* Static blog template
   * https://codesandbox.io/s/dojo-blog-template-2lezs
* Working with resize middleware
   * https://codesandbox.io/s/mzqk41j319
* Working with Dojo store and arrays (also store middleware)
   * https://codesandbox.io/s/upbeat-satoshi-qk1jo9lzzw

**Comment by KaneFreeman** [comment]
With the new @dojo/widgets site, I will be excluding the @dojo/widget codesandbox examples in favor of #174
