### ISSUE TITLE
Constrain width of text content to improve readability

### ISSUE THREAD

**Issue by msssk** [dojo/site#164]
Page content expands to fill available width. On a big screen this can result in difficult to read text. A max width of around 60em improves readability.

Screenshots below show the [Learn page](https://dojo.io/learn/overview/introduction), but the landing page layout could also benefit from some max-width consideration.

Current site:
![dojo io wide](https://user-images.githubusercontent.com/931637/63873815-1e680180-c975-11e9-8e87-dbfd08748a00.png)

`max-width: 60em`:
![dojo io constrained](https://user-images.githubusercontent.com/931637/63873827-258f0f80-c975-11e9-827f-5010e7f50d9b.png)

**Comment by agubler** [comment]
resolved by #176
