### ISSUE TITLE
Show the widget documentation on site

### ISSUE THREAD

**Issue by matt-gadd** [dojo/site#174]
We are currently not surfacing the widget documentation/readme's at all on site.

We should explore pulling the readme's into site and and a way to browse them in some list or similar.

As a follow on/stretch goal this could extend to being able to surface the properties interface (which are effectively the public api) for each widget also.

**Comment by jellison** [comment]
This was resolved on the Widget side with dojo/widgets#806

**Comment by KaneFreeman** [comment]
There needs to be some link added to site to the https://widgets.dojo.io
