### ISSUE TITLE
Blog Compatibility Plan [RSS]

### ISSUE THREAD

**Issue by nicknisi** [dojo/site#25]
We want to make sure that we have a strategy around a seamless compatibility between the old site and the new.

- The URLs to blog posts should be the exact same
- The RSS generated should be the same
- We should try not to spam RSS feeds with all existing posts when the new site goes live.

**Comment by KaneFreeman** [comment]
URLs will not be an issue. Its the RSS setup that really needs worked on with this.

**Comment by KaneFreeman** [comment]
@grayrest, the outstanding parts of this are:

1. Transferring all blogs over from the old site to the new.
2. Setting up redirects for the old blog URLs to their new ones. Might be a @matt-gadd thing

**Comment by grayrest** [comment]
If the old and the new urls are different, there's no way to keep the RSS the same and not spam existing posts unless we simply don't include existing posts in the RSS feed.
