### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by matt-gadd** [dojo/site#3]
Open to experimentation?! Failing that we could port the existing page to use the real intersection meta, create a fancy terminal widget to display the cli stuff use a real custom element for the menu? In general the front page could do with some love.

**Comment by KaneFreeman** [comment]
@JamesMilnerUK The following responsive issues exist in the current prod deployment.

- **Tablet** - Page width grows as CLI section typing occurs. Tested in Chrome with iPad Pro in Portrait mode (width: 1024).
  ![home-page-shift](https://user-images.githubusercontent.com/1388138/54314174-59d26780-45b1-11e9-9a91-23863e7bd910.gif)
- **Large Monitor / Laptop** - The :heavy_check_mark: Success message in the CLI section moves relative to the rest of the section, causing inconsistent layout.
  - Large Monitor: 
    ![image](https://user-images.githubusercontent.com/1388138/54313661-2b07c180-45b0-11e9-80dd-81e4887e069b.png)
  - Laptop: 
    ![image](https://user-images.githubusercontent.com/1388138/54313704-3e1a9180-45b0-11e9-93bf-fa673ba8eb5c.png)

**Comment by KaneFreeman** [comment]
Just need link for `Build with Dojo` from content.
