### ISSUE TITLE
Doc/Tutorial technology

### ISSUE THREAD

**Issue by brucou** [dojo/site#40]
Hey there,

I have a quick question. Do you have a static site generator for the documentation and tutorial portion on your website? Which would that be? Could not find any credit on the pages. It is pretty neat, was just wondering if I could use whatever it is use that you are using, unless it is proprietary stuff.

**Comment by KaneFreeman** [comment]
@brucou We are using [remark/parse](https://github.com/remarkjs/remark/tree/master/packages/remark-parse) and [remark/macro](https://github.com/dimerapp/remark-macro) to convert markdown files to VNode/WNode elements during the dojo build process using a new Build Time Rendering (BTR) capability in Dojo 5 called Blocks (see https://dojo.io/blog/2019/01/29/2019-01-29-Version-5-Dojo/ for more information).

This is the script connecting up the pieces: https://github.com/dojo/site/blob/master/src/scripts/compile.block.ts

**Comment by brucou** [comment]
Thanks Kane! Will dive into Dojo then
