### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by matt-gadd** [dojo/site#5]
Examples are currently criminally under marketed, they're not listed on dojo.io at all I don't think? It would be nice if they were nicely listed on the with any meta information we can, along with thumbnails (perhaps from codesandbox?), and runnable in codesandbox. 
https://github.com/dojo/examples

**Comment by KaneFreeman** [comment]
Would probably be a good place to use another `.block` setup to parse out the relevant details from the dojo/examples git repo (most likely the readme).
