### ISSUE TITLE
Make it useable without JavaScript

### ISSUE THREAD

**Issue by JamesMilnerUK** [dojo/site#71]
We should progressively enhance the site so that it is functional without JavaScript.

**Comment by KaneFreeman** [comment]
| Page | Loads with JS Off | Note |
| --- | :---: | --- |
| Home | ✔️ |  |
| Menu / Header | ✔️ |  |
| Blog | ❔ |  |
| Tutorials Landing | ❔ |   |
| Tutorials | ❔ |  |
| Reference Guides Landing | ✔️ |  |
| Reference Guides | ✔️ |  |
| Examples | ❌ |  |
| Playground | 🚫  | Not expected to work, as it is loading Codesandbox |
| Roadmap | ❔ |  |
| Community | ✔️ |  |

## Details
- **Blog** - In progress in #1 
- **Roadmap ** - In progress in #7 
- **Tutorials / Tutorials Landing** - Removed from prod build for now.
- **Examples**: CSS not loading - Opened #80 to address.
