### ISSUE TITLE
Parent Menu Item Highlighting in Hamburger Menu

### ISSUE THREAD

**Issue by KaneFreeman** [dojo/site#95]
Need to find better option for highlighting parent menu items in the hamburger menu. Currently it is using a lifecycle hook in two place (`Header` widget and `ReferenceGuideMenu` widget) to achieve this.

```
	protected onAttach() {
		const item = this.registry.getInjector<Router>('router');
		if (item) {
			const router = item.injector();
			router.on('outlet', () => {
				this.invalidate();
			});
		}
	}
```

**Discussion so far**:
![image](https://user-images.githubusercontent.com/1388138/54845025-ae12d100-4cae-11e9-9329-d2edcee8ad0e.png)

**Comment by agubler** [comment]
Since re-working the menu and document sections this is no longer an issue.
